version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    environment:
      # Si tu as besoin d'ajouter des variables d'environnement pour le frontend, fais-le ici
      # EX: API_URL: "http://backend-service:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    environment:
      # Si tu as besoin d'ajouter des variables d'environnement pour le backend, fais-le ici
      # EX: DB_HOST: "mongodb://db-service:27017"

